### PR TITLE
add links to protocol guide and ssb.nz

### PR DESCRIPTION
**Pull request by cblgh**
one of the outcomes of the documentation sprint: sprinkling a few links inside the existing dev docs to make the other sites easier to find :)

in particular, one good fix is adding a link to the protocol guide inside the developer docs :~

there's a preview embedded belowimage

### CODE REVIEW

**Comment by cblgh** [comment]
cc @mixmix @arj03 @cryptix since i'm not part of the ssbc org

**Comment by cblgh** [comment]
@arj03 haha oh no i accidentally created two pull requests! this one was the more up to date one XD

**Comment by cblgh** [comment]
(the original one was supposed to be for merging into master of my fork lol)

**Comment by arj03** [comment]
Ah :) Anyway nice work on this. I have added you to the ssbc org.

**Comment by arj03** [comment]
In the ssb-ngi-pointer org we have a good pattern (I believe) where all changes go through a PR and an approval by someone else. I like that pattern and see it as healthy, so I'd be nice to use it in this repo I think :)

**Pull request merged**
