### PR TITLE
Add basic documentation for the Sunrise Choir Rust implementation

### PR DESCRIPTION
**Pull request by mycognosist**
This PR adds the following sections to the Sunrise Choir implementation page:

- Introduction: various repo and documentation links
- SSB-Keyfile: how to generate, read and write keys
  - Signing: how to sign an object and create a Message
  - Verification: how to verify the fields and signature of a signed object
- Cryptography: background and links for cryptographic code and documentation
  - Verification: how to verify the signature of an entire ssb message (or collection of messages)
  - Validation: how to validate a message hash chain or feed hash chain (collection of messages)
- TODO
- Contact: contact details for the developers and documentor

I have also created a playground repo containing the code examples from the docs: [sunrise-ssb-playground](https://github.com/mycognosist/sunrise-ssb-playground). I find it's often nice to have actual executable code when learning to navigate and use a new library.

### CODE REVIEW

**Comment by arj03** [comment]
This looks great, especially like the playground. Wish I had to time to dig into the rust side of things, but *must* resist the temptation. If I would this would be the perfect companion guide.

**Comment by mycognosist** [comment]
Making good progress. The highlight of my day was seeing a successful handshake between the async client and server examples I've created in the playground (had to sweat a little to figure it out).

Updates since my initial comment to open this PR:

- SSB Multiformats: how to parse references for feeds, messages and blobs
- Peer Connections
  - Network Key: how to generate a unique network key or use the main network key
  - Discovery: how to discover peers (high-level overview, no implementation details)
  - Secret Handshake: how to initiate a secret handshake from a server and client
  
I'm in touch with Piet who has already offered great assistance.

**Comment by mycognosist** [comment]
Updates since my last comment:

- Peer Connections
  - Box Stream: how to create a new boxstream, write to it and read from it
  - Packet Stream (RPC protocol): how to create a sink and a stream, craft a packet, write and read packets etc.

I have also pushed example code corresponding to these doc additions to the playground repo.

I think this would be a good point to merge this. I'll probably make some minor changes in the future to make the tone of the writing more consistent and to improve flow and readability, but for now it seems like a solid foundation 🙂

**Comment by arj03** [comment]
This is fantastic! Have been following along on the side line :-)

**Comment by mycognosist** [comment]
@arj03 Thanks for all the encouragement and support! ❤️

**Pull request merged**
